Repository thoth-station/si-cloc, pull requests merged in 2020-09, with the labels that each got.

#27 Automatic update of dependency thoth-common from 0.14.2 to 0.18.3
  Pipfile.lock
Labels: approved, bot, size/M

#28 Add version logs
  app.py
Labels: approved

#32 Makre pre-commit happy
  app.py
Labels: approved, size/S

#30 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/S

#34 Release of version 0.1.3
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S
