Repository thoth-station/si-cloc, pull requests merged in 2020-06, with the labels that each got.

#6 Do not ship Pipenv
  Dockerfile
Labels: approved, size/XS

#8 Oc argo templates
  openshift/buildConfig.yaml
  openshift/imageStream-template.yaml
  openshift/si-cloc-template.yaml
  workflows/templates/cloc-template.yaml
Labels: approved, size/L

#7 Automatic update of dependency thoth-common from 0.13.10 to 0.13.11
  Pipfile.lock
Labels: bot, size/S

#5 cloc container image based on f32-py38
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#12 Automatic update of dependency thoth-common from 0.13.11 to 0.13.12
  Pipfile.lock
Labels: approved, bot, ok-to-test, size/XS

#11 Use the s2i-thoth-f32-py38-cloc base image
  openshift/buildConfig.yaml
Labels: approved, size/XS

#16 Automatic dependency re-locking
  Pipfile.lock
Labels: approved, bot, size/M
