Repository thoth-station/si-cloc, pull requests merged in 2020-07, with the labels that each got.

#17 Automatic update of dependency thoth-common from 0.13.13 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/S

#18 now part of thoth-application
  openshift/buildConfig.yaml
  openshift/imageStream-template.yaml
  openshift/si-cloc-template.yaml
Labels: approved, size/L

#21 Release of version 0.1.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#20 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#24 include aicoe-ci configuration file
  .aicoe-ci.yaml
Labels: approved, size/S

#23 Release of version 0.1.2
  CHANGELOG.md
  app.py
Labels: approved, bot, size/M

#25 migrated to thoth-application
  .zuul.yaml
  workflows/templates/cloc-template.yaml
Labels: approved, size/M
